## script to build 2024 workshop table

data <- list(
  list(date = "Oct 21, 11:00-15:00 EDT \\*",
       title = "Diversity Alliance Hackathon",
       people = "members of R/Pharma community"),
  list(date = "Oct 25, 09:00-11:00 EDT",
       title = "Parameterised plots and reports with R and Quarto",
       people = "Nicola Rennie (University of Lancaster)"),
  list(date = "Oct 25, 10:00-13:00 EDT",
       title = "Building ADaMs with pharmaverse R packages admiral, metacore/metatools and xportr",
       people = "Ben Straub (GSK), Fanny Gautier (Cytel), Edoardo Mancini (Roche)"),
  list(date = "Oct 25, 13:00-15:00 EDT",
       title = "{shinylive}: Serverless Shiny applications workshop. An exercise in deploying your App to GitHub Pages",
       people = "Barret Schloerke (posit)"),
  list(date = "Oct 25, 13:00-16:00 EDT",
       title = "{shinylive}Knowledge graphs for drug discovery",
       people = "Thomas Charlon (Harvard Medical School)"),
  list(date = "Oct 25, 15:00-17:00 EDT",
       title = "Preview of Posit Administrator Training",
       people = "Shannon Hagerty (posit)"),
  list(date = "Oct 25, 15:00-17:00 EDT",
       title = "Tables in Python with great tables",
       people = "Rich Iannone (posit), Michael Chow (posit)"),
  list(date = "Oct 28, 00:00-03:10 EDT \\*\\*",
       title = "Good Software Engineering Practice for R Packages",
       people = ""),
  list(date = "Oct 28, 09:00-11:30 EDT",
       title = "The Near-Future of Regulatory Submissions: Embracing Reproducibility, Open Source, and Interactivity",
       people = "Leena Khatri (Roche), Davide Garolini (Roche)"),
  list(date = "Oct 28, 11:00-13:00 EDT",
       title = "Shiny Application Development and Validation with Rhino",
       people = "Deepansh Khurana (Appsilon)"),
  list(date = "Oct 28, 12:00-14:00 EDT",
       title = "SDTM programming in R using {sdtm.oak} package",
       people = "Rammprasad Ganapathy (Genentech)"),
  list(date = "Oct 28, 13:00-15:00 EDT",
       title = "Bayesian Dose-Response Modeling with the dreamer R Package",
       people = "Richard Payne (Eli Lilly)"),
  list(date = "Oct 28, 13:00-16:00 EDT",
       title = "Unlocking Analysis Results Datasets: A Practical Workshop for Creating and Utilizing ARDs for Clinical Reporting",
       people = "Daniel Sjoberg(Genentech), Becca Krouse (GSK)"),
  list(date = "Oct 28, 23:00-Oct 29, 02:10 EDT \\*\\*",
       title = "Reproducible and scalable reporting using rmarkdown & heddlr",
       people = ""),
  list(date = "Nov 1, 09:00-12:00 EDT",
       title = "Selected examples on how to scale-up computations in R (e.g. by using HPC)",
       people = "Michael Mayer (posit)"),
  list(date = "Nov 1, 09:00-12:00 EDT",
       title = "No code data analysis with blockr",
       people = "David Granjon (Cynkra), Karma Tarap (BMS), John Coene (Y Company)"),
  list(date = "Nov 1, 11:00-13:00 EDT",
       title = "R Validation Hub Risk Tools Developer Day",
       people = "Doug Kelkhoff (Roche)"),
  list(date = "Nov 1, 13:00-15:30 EDT",
       title = "Visualizing Clinical Trial Data: Foundational Principles for Data Visualization, Best Practices, and Programming Techniques in R by Example",
       people = "Joshua Cook (USC Big Data Health Science Center)"),
  list(date = "Nov 1, 14:00-16:00 EDT",
       title = "The Expanse: Creating R Packages for Statisticians",
       people = "Ben Arancibia (GSK)")
)

rtn <- data |>
  dplyr::bind_rows() |>
  glue::glue_data('| {date} | <p style="font-weight: 600; margin-bottom: .1rem;">{title}</p><p style="font-size: .8em; margin-bottom: .2rem;">{people}</p> |')
