---
title: "Terms and conditions"
output: html_document
---

# Key Notes:

* This is a free event brought to you by passionate volunteers
* By signing up, you agree that R/Pharma assumes no responsibility, and any costs, annoyances or catastrophic events incurred due to attending this conference are yours and yours alone
* We’ll take some photos and audio recordings of the talks. Please don’t take recordings of other participants without their permission. * Please let us know if you prefer not to have your talk recorded. While participating in the group activities, your photo may be taken and be posted on the group website. It is your responsibility to inform others if you do not wish to be photographed and inform us if any of your photos to be removed.
* Please don’t share content at R/Pharma unless you have permission to do so.
* This is a free event and invites/tickets cannot be transferred or exchanged without permission of the Organizing Committee. In the unlikely occurrence that R in Pharma to be cancelled or postponed due to circumstances beyond the control, we cannot be held responsible for any costs incurred by the event attendee.
* Speakers are subject to change and we do not guarantee that any specific speakers or participants will appear at the event. However, we will always try to find a suitable replacement if one of our key speakers or participants is unable to attend. Views expressed by speakers at the event may not be the views of R in Pharma.
* Event materials are provided on an “as is” basis and R in Pharma makes no warranty regarding the accuracy or completeness of those materials.

# Diversity:

R/Pharma is dedicated to providing a harassment-free conference experience for everyone regardless of gender, sexual orientation, disability or any feature that distinguishes human beings. For more information, please see the R Consortium code of conduct. https://wiki.r-consortium.org/view/R_Consortium_and_the_R_Community_Code_of_Conduct 
 

# Policy Statement of the R in Pharma Conference:

The purpose of the R in Pharma conference is to foster discussion on the use of R in the pharmaceutical industry. R in Pharma is not, and hopefully never will be a commercially oriented meeting. As such, we do not accept administrative responsibility for distributing commercial materials, nor do we allow vendors to participate in the meeting in any role other than as scientists/practitioners interested in learning or discussing the application of R in Pharma. All attendees are requested to adhere to the spirit of this policy. Please don’t spam attendees.

# Terms
R/Pharma is free event and comes with ABSOLUTELY NO WARRANTY. YOUR PARTICIPATION IS AT YOUR SOLE AND EXCLUSIVE RISK. By accepting the invitation to attend and registering a ticket, you freely and voluntarily assume all risks. You also agree not to hold organizers responsible for their negligence in connection with the conference or Content or events.

R/Pharma assumes no responsibility for any costs (e.g. travel) in any circumstance, examples including if the conference is cancelled, or named speakers are unable to attend.

You agree to indemnify, defend, and hold R/Pharma and all parites and its subsidiaries, affiliates, officers, directors, agents, co-branders or other partners, employees, and representatives harmless from and against any and all claims, damages, losses, costs or expenses (including reasonable attorneys’ fees and disbursements) which arise directly or indirectly out of or from (i) your breach of this Agreement, (ii) any allegation that any materials that you submit to R/Pharma or present (e.g., conference, github, website) infringe or otherwise violate the copyright, trade secret, trademark or other intellectual property rights of a third party, and (iii) your access or use of the Sites and/or the Services.

NOTWITHSTANDING ANYTHING TO THE CONTRARY HEREIN, TO THE FULLEST EXTENT ALLOWED BY LAW, YOU AGREE TO WAIVE, DISCHARGE CLAIMS, RELEASE All Parties FROM ALL LIABILITY AND INDEMNIFY AND HOLD HARMLESS ORGANIZERS, HOSTS, SUBSIDIARIES, AFFILIATES, OFFICERS, AGENTS, VOLUNTEERS AND OTHER PARTNERS AND EMPLOYEES, FROM ANY AND ALL LIABILITY ON ACCOUNT OF, OR IN ANY WAY RESULTING FROM INJURIES AND DAMAGES IN ANY WAY CONNECTED WITH ANY EVENTS OR ACTIVITIES.

# Notes
No confidential information should be disclosed at meetings and no warranty of confidentiality is made by the event organizers. Audio Recordings of events may be taken by event organizers and general content may be used in discussion postings or meeting highlights on our website, github or used elsewhere. Attendees of events acknowledge this content may be shared and release the event organizers to use this content freely. Audio or video recordings of events by attendees are prohibited. We will not share information if you request we do not do so.

Visit https://www.r-consortium.org/about/governance for more info.
