# (PART) Overview {-}

# Schedule

<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
 <thead>
  <tr>
   <th style="text-align:left;"> When </th>
   <th style="text-align:left;"> What </th>
   <th style="text-align:left;"> Who </th>
  </tr>
 </thead>
<tbody>
  <tr grouplength="1"><td colspan="3" style="background-color: #666; color: #fff;"><strong>Tuesday</strong></td></tr>
<tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 18:00 - 21:30 </td>
   <td style="text-align:left;"> Pre-conference Dinner </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="31"><td colspan="3" style="background-color: #666; color: #fff;"><strong>Wednesday</strong></td></tr>
<tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 07:30 - 09:15 </td>
   <td style="text-align:left;"> Registration </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 08:00 - 09:00 </td>
   <td style="text-align:left;"> Workshop </td>
   <td style="text-align:left;"> Keeping things Peachy when Shiny gets Hairy </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 08:00 - 09:00 </td>
   <td style="text-align:left;"> Workshop </td>
   <td style="text-align:left;"> Analyzing Clinical Trials Data with R </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 08:00 - 09:00 </td>
   <td style="text-align:left;"> Workshop </td>
   <td style="text-align:left;"> Stan for Pharma </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 08:00 - 09:00 </td>
   <td style="text-align:left;"> Workshop </td>
   <td style="text-align:left;"> Moving Fast Without Breaking Things: Navigating the R Ecosystem in an Enterprise Environment </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 09:15 - 09:25 </td>
   <td style="text-align:left;"> Opening Remarks </td>
   <td style="text-align:left;"> Richard McCullough, Ph.D. Vice Provost of Research, Harvard University </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 09:25 - 10:10 </td>
   <td style="text-align:left;"> Keynote </td>
   <td style="text-align:left;"> Modernizing the new drug regulatory program in FDA/CDER:  Can Collaborations and Sharing Help? **(Lilliam Rosario)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 10:10 - 10:30 </td>
   <td style="text-align:left;"> Talk </td>
   <td style="text-align:left;"> Using R in a regulatory environment: some FDA perspectives **(Paul Schuette)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 10:30 - 10:40 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Using R in a GxP Environment **(Boyd Gonnerman, et. al.)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 10:40 - 10:50 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> IDBac: A New Paradigm in Developing Microbial Libraries for Drug Discovery **(Chase Clark)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 10:50 - 11:10 </td>
   <td style="text-align:left;"> Break </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 11:10 - 11:30 </td>
   <td style="text-align:left;"> Talk </td>
   <td style="text-align:left;"> The largest Shiny application in the world. Roche.Diagnostics.bioWARP **(Sebastian Wolf)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 11:30 - 11:40 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> R reproducibility by containers and cloud **(Reinhold Koch)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 11:40 - 11:50 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Multi-state Model for the Analysis of an Association between Safety and Efficacy Events **(Juliane Manitz)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 12:10 - 13:30 </td>
   <td style="text-align:left;"> Lunch </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 13:30 - 13:40 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Becoming bilingual in SAS and R **(Bella Feng)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 13:40 - 13:50 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Visualization methods for RNA-sequencing data analysis **(Lindsay Rutter)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 13:50 - 14:00 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> The Use of R in the Development of Physiological Model for Healthy Growth **(Rena J. Eudy-Byrne)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 14:00 - 14:10 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Antibody Characterization Using Next Generation Sequencing made easier with Group My Abs shiny app. **(Volha Tryputsen)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 14:10 - 14:20 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Managing R and Associated Tools in Large Environments - an R-Admin’s Perspective **(Edward Lauzier)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 14:20 - 14:50 </td>
   <td style="text-align:left;"> Break </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 14:50 - 15:35 </td>
   <td style="text-align:left;"> Keynote </td>
   <td style="text-align:left;"> Modeling in the tidyverse **(Max Kuhn)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 15:35 - 15:55 </td>
   <td style="text-align:left;"> Talk </td>
   <td style="text-align:left;"> ShinyRAP - a framework for analysis and building interactive/dynamic reports using Shiny/Markdown **(Xiao Ni)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 15:55 - 16:05 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Data-Driven Strategies for Synthetic Route Design and Operational Modeling within Pharmaceutical Development **(Jun Li)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 16:05 - 16:15 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Evaluating the performance of advanced causal inference methods applied to healthcare claims data **(Jessica Myers Franklin)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 16:15 - 16:25 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Optimization of raw materials genealogy in drug manufacturing with R, Shiny and d3 **(Tanya Cashorali)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 16:25 - 16:35 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> REAP - R-Shiny Exploratory Analysis Platform in Clinical Pharmacology **(Qi Liu)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 16:35 - 16:45 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> rOpenSci - enabling open and reproducible research **(Stefanie Butland)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 16:45 - 17:05 </td>
   <td style="text-align:left;"> Talk </td>
   <td style="text-align:left;"> Moving Fast Without Breaking Things: Navigating the R Ecosystem in an Enterprise Environment **(Devin Pastoor)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 17:05 - 17:25 </td>
   <td style="text-align:left;"> Talk </td>
   <td style="text-align:left;"> Beyond Simple Reproducibility - Discoverability, Provenance, and Improving the Impact of Results **(Gabe Becker)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 18:00 - 19:30 </td>
   <td style="text-align:left;"> Reception </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr grouplength="31"><td colspan="3" style="background-color: #666; color: #fff;"><strong>Thursday</strong></td></tr>
<tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 07:30 - 09:15 </td>
   <td style="text-align:left;"> Registration </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 08:00 - 09:00 </td>
   <td style="text-align:left;"> Workshop </td>
   <td style="text-align:left;"> Interactive data visualization with R, plotly, and dashR </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 08:00 - 09:00 </td>
   <td style="text-align:left;"> Workshop </td>
   <td style="text-align:left;"> The Challenges of Validating R </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 08:00 - 09:00 </td>
   <td style="text-align:left;"> Workshop </td>
   <td style="text-align:left;"> The largest Shiny application in the world. Roche.Diagnostics.bioWARP </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 09:15 - 09:25 </td>
   <td style="text-align:left;"> Opening Remarks </td>
   <td style="text-align:left;"> Dustin Tingley, Ph.D., Professor of Government, Harvard University </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 09:25 - 10:10 </td>
   <td style="text-align:left;"> Keynote </td>
   <td style="text-align:left;"> Using interactivity responsibly in pharma **(Joe Cheng)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 10:10 - 10:30 </td>
   <td style="text-align:left;"> Talk </td>
   <td style="text-align:left;"> Interactive data visualization with R, plotly, and dashR **(Carson Sievert)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 10:30 - 10:50 </td>
   <td style="text-align:left;"> Talk </td>
   <td style="text-align:left;"> Developing powerful Shiny applications in an enterprise environment: Best practices and lessons learned **(Eric Nantz)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 10:50 - 11:10 </td>
   <td style="text-align:left;"> Break </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 11:10 - 11:30 </td>
   <td style="text-align:left;"> Talk </td>
   <td style="text-align:left;"> NetTCR: Towards Accurate Prediction of T-cell Targets using Deep Learning **(Leon Eyrich Jessen)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 11:30 - 11:50 </td>
   <td style="text-align:left;"> Talk </td>
   <td style="text-align:left;"> Analyzing Clinical Trials Data with R **(Adrian Waddell)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 12:10 - 13:30 </td>
   <td style="text-align:left;"> Lunch </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 13:30 - 13:40 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Unification in a Compartmentalized Culture **(Mat Soukup)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 13:40 - 13:50 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> R4SPA: R Packages and Training to enable Statistical Programming in R **(Kieran Martin)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 13:50 - 14:00 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Assisting pharmacometric simulation with the use of Shiny **(Jia Kang)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 14:00 - 14:10 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> R/Shiny Clinical Dashboards For Fun* and Profit *Note: Fun is Relative **(Nate Mockler)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 14:10 - 14:20 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> The drake R package: reproducible data analysis at scale **(Will Landau)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 14:20 - 14:50 </td>
   <td style="text-align:left;"> Break </td>
   <td style="text-align:left;">  </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 14:50 - 15:35 </td>
   <td style="text-align:left;"> Keynote </td>
   <td style="text-align:left;"> Enabling open-source analytics in the enterprise **(Michael Lawrence)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 15:35 - 15:45 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> The role of R in converting clinical trial programmers to data scientists **(James Black)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 15:45 - 15:55 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Accelerate Personalized Health Care by Empowering Biomarker Data **(Xiuting Mi)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 15:55 - 16:05 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Keeping things Peachy when Shiny gets Hairy **(Marianna Foos)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 16:05 - 16:15 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Shiny Apps in Genomics and Clinical Trials **(Jessica Minnier)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 16:15 - 16:25 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> R as the Core Technology to Support Modeling and Simulation in Pharma Research, Development, and Post Approval Activities **(Marc Gastonquay)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 16:25 - 16:35 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Building a community of competent developers and users of R-based tools in mass spectrometry-based research **(Olga Vitek)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 16:35 - 16:45 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Bayesian Models for Smaller Trial Sizes **(Daniel Lee)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 16:45 - 16:55 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Enhance R Overview **(Jay Timmerman)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 16:55 - 17:05 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> The Magic R-Shiny App that can Boost your SDTM Usability and Viability while Saving Time **(Elma Zannatul Ferdousy &amp; Katrina Paz)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 17:05 - 17:15 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> Reproducible computational research at Eisai: leadership, technology, and culture **(Joseph Gerrein)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 17:15 - 17:25 </td>
   <td style="text-align:left;"> Lightning Talk </td>
   <td style="text-align:left;"> The Challenges of Validating R **(Andy Nicholls)** </td>
  </tr>
  <tr>
   <td style="text-align:left; padding-left: 2em;" indentlevel="1"> 18:00 - 20:00 </td>
   <td style="text-align:left;"> Drinks </td>
   <td style="text-align:left;">  </td>
  </tr>
</tbody>
</table>

## Wednesday

This is the shortened schedule, please go to [the Full Schedule](http://rinpharma.com/program/schedule.html) for more detailed information.

| When | What | 
|----|----| 
* **07:30 - 09:15** _Registration_ 
* **08:00 - 09:00** _Keeping things Peachy when Shiny gets Hairy (Workshop)_ 
* **08:00 - 09:00** _Analyzing Clinical Trials Data with R (Workshop)_ 
* **08:00 - 09:00** _Stan for Pharma (Workshop)_ 
* **08:00 - 09:00** _Moving Fast Without Breaking Things: Navigating the R Ecosystem in an Enterprise Environment (Workshop)_ 
* **09:15 - 09:25** _Opening Remarks_ 
* **09:25 - 10:10** _Modernizing the new drug regulatory program in FDA/CDER:  Can Collaborations and Sharing Help?_ 
* **10:10 - 10:30** _Using R in a regulatory environment: some FDA perspectives_ 
* **10:30 - 10:40** _Using R in a GxP Environment_ 
* **10:40 - 10:50** _IDBac: A New Paradigm in Developing Microbial Libraries for Drug Discovery_ 
* **10:50 - 11:10** _Break_ 
* **11:10 - 11:30** _The largest Shiny application in the world. Roche.Diagnostics.bioWARP_ 
* **11:30 - 11:40** _R reproducibility by containers and cloud_ 
* **11:40 - 11:50** _Multi-state Model for the Analysis of an Association between Safety and Efficacy Events_ 
* **12:10 - 13:30** _Lunch_ 
* **13:30 - 13:40** _Becoming bilingual in SAS and R_ 
* **13:40 - 13:50** _Visualization methods for RNA-sequencing data analysis_ 
* **13:50 - 14:00** _The Use of R in the Development of Physiological Model for Healthy Growth_ 
* **14:00 - 14:10** _Antibody Characterization Using Next Generation Sequencing made easier with Group My Abs shiny app._ 
* **14:10 - 14:20** _Managing R and Associated Tools in Large Environments - an R-Admin’s Perspective_ 
* **14:20 - 14:50** _Break_ 
* **14:50 - 15:35** _Modeling in the tidyverse_ 
* **15:35 - 15:55** _ShinyRAP - a framework for analysis and building interactive/dynamic reports using Shiny/Markdown_ 
* **15:55 - 16:05** _Data-Driven Strategies for Synthetic Route Design and Operational Modeling within Pharmaceutical Development_ 
* **16:05 - 16:15** _Evaluating the performance of advanced causal inference methods applied to healthcare claims data_ 
* **16:15 - 16:25** _Optimization of raw materials genealogy in drug manufacturing with R, Shiny and d3_ 
* **16:25 - 16:35** _REAP - R-Shiny Exploratory Analysis Platform in Clinical Pharmacology_ 
* **16:35 - 16:45** _rOpenSci - enabling open and reproducible research_ 
* **16:45 - 17:05** _Moving Fast Without Breaking Things: Navigating the R Ecosystem in an Enterprise Environment_ 
* **17:05 - 17:25** _Beyond Simple Reproducibility - Discoverability, Provenance, and Improving the Impact of Results_ 
* **18:00 - 19:30** _Reception_ 


## Thursday

This is the shortened schedule, please go to [the Full Schedule](http://rinpharma.com/program/schedule.html) for more detailed information.

* **07:30 - 09:15** _Registration_ 
* **08:00 - 09:00** _Interactive data visualization with R, plotly, and dashR (Workshop)_ 
* **08:00 - 09:00** _The Challenges of Validating R (Workshop)_ 
* **08:00 - 09:00** _The largest Shiny application in the world. Roche.Diagnostics.bioWARP (Workshop)_ 
* **09:15 - 09:25** _Opening Remarks_ 
* **09:25 - 10:10** _Using interactivity responsibly in pharma_ 
* **10:10 - 10:30** _Interactive data visualization with R, plotly, and dashR_ 
* **10:30 - 10:50** _Developing powerful Shiny applications in an enterprise environment: Best practices and lessons learned_ 
* **10:50 - 11:10** _Break_ 
* **11:10 - 11:30** _NetTCR: Towards Accurate Prediction of T-cell Targets using Deep Learning_ 
* **11:30 - 11:50** _Analyzing Clinical Trials Data with R_ 
* **12:10 - 13:30** _Lunch_ 
* **13:30 - 13:40** _Unification in a Compartmentalized Culture_ 
* **13:40 - 13:50** _R4SPA: R Packages and Training to enable Statistical Programming in R_ 
* **13:50 - 14:00** _Assisting pharmacometric simulation with the use of Shiny_ 
* **14:00 - 14:10** _R/Shiny Clinical Dashboards For Fun* and Profit *Note: Fun is Relative_ 
* **14:10 - 14:20** _The drake R package: reproducible data analysis at scale_ 
* **14:20 - 14:50** _Break_ 
* **14:50 - 15:35** _Enabling open-source analytics in the enterprise_ 
* **15:35 - 15:45** _The role of R in converting clinical trial programmers to data scientists_ 
* **15:45 - 15:55** _Accelerate Personalized Health Care by Empowering Biomarker Data_ 
* **15:55 - 16:05** _Keeping things Peachy when Shiny gets Hairy_ 
* **16:05 - 16:15** _Shiny Apps in Genomics and Clinical Trials_ 
* **16:15 - 16:25** _R as the Core Technology to Support Modeling and Simulation in Pharma Research, Development, and Post Approval Activities_ 
* **16:25 - 16:35** _Building a community of competent developers and users of R-based tools in mass spectrometry-based research_ 
* **16:35 - 16:45** _Bayesian Models for Smaller Trial Sizes_ 
* **16:45 - 16:55** _Enhance R Overview_ 
* **16:55 - 17:05** _The Magic R-Shiny App that can Boost your SDTM Usability and Viability while Saving Time_ 
* **17:05 - 17:15** _Reproducible computational research at Eisai: leadership, technology, and culture_ 
* **17:15 - 17:25** _The Challenges of Validating R_ 
* **18:00 - 20:00** _Drinks_ 
