# (PART) Talks {-}

# Keynotes

## _Modernizing the new drug regulatory program in FDA/CDER:  Can Collaborations and Sharing Help?_

**Lilliam Rosario**, FDA Center for Drug Evaluation & Research

_Wednesday, 15th August from 09:25 - 10:10_

Lilliam will be presenting a perspective on what the office of computational science is doing to support regulatory review for safety assessments. She will explore the concept of collaborations and sharing to support process and transparency, along with a perspective with the use of R.

## _Modeling in the tidyverse_

**Max Kuhn**, RStudio

_Wednesday, 15th August from 14:50 - 15:35_

The tidyverse (tidyverse.org) is an opinionated collection of R packages designed for data science. All packages share an underlying design philosophy, grammar, and data structures. The packages primarily consist of tools for data ingest, manipulation, and visualization. In the last year or so, Rstudio and others have been creating a set of packages focused on the modeling process. In this talk, we will introduce the tidyverse and illustrate these new tools whose goals are to: simplify the modeling process, encourage empirical validation and good methodology, and to enable a wider variety of approaches.

## _Using interactivity responsibly in pharma_

**Joe Cheng**, RStudio

_Thursday, 16th August from 09:25 - 10:10_

Shiny is a package for turning analyses written in R into interactive web applications. This capability has obvious applications in pharma, as it lets R users build interactive apps for their collaborators to explore models or results, or to automate workflows. However, the interactivity of Shiny apps is a double-edged sword, as it introduces challenges to the traceability and reproducibility of your analysis. To use interactive applications in pharma responsibly, these challenges must be addressed. In this talk, I'll look at some of the tools and techniques you can use in Shiny to deal with these challenges head-on.

## _Enabling open-source analytics in the enterprise_

**Michael Lawrence**, Genentech, R Core Team

_Thursday, 16th August from 14:50 - 15:35_

The open-source analytics community is driving innovation in precompetitive spaces like statistical methodology, reproducibility approaches, visualization techniques, and scaling strategies. The diverse and rapdily evolving ecosystem of open-source tools and standards stands in contrast with the disposition of the enterprise towards stability, standardization, and reliability. This talk will present the policies and frameworks we have developed at Genentech to enable internal scientists to responsibly leverage open-source tools and to participate in the community process through their own contributions.
